---
apiVersion: v1
kind: Service
metadata:
  name: clickcount-redis
spec:
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
    protocol: TCP
  selector:
    app: clickcount
    role: database

---
apiVersion: v1
kind: Service
metadata:
  name: clickcount-service
  labels:
    app: clickcount
spec:
  type: ClusterIP
  ports:
  - port: 8080
  selector:
    app: clickcount
    role: frontend
